require('plugins.packer')
require('plugins.lsp.lsp-installer')
require('plugins.lsp.lspconfig')
require('plugins.themes.vscode')
require('plugins.nvim-tree')
require('plugins.treesitter')
require('plugins.lualine')
require('plugins.telescope')
require('user.options')
require('user.keymaps')

