require('plugins.packer')
require('plugins.lsp')
require('plugins.themes.vscode')
require('plugins.nvim-tree')
require('plugins.treesitter')
require('plugins.lualine')
require('plugins.telescope')
require('plugins.cmp')
